#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlumniSNS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="AlumniSNS")]
	public partial class AlumniSNSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertEnrollProgram(AlumniSNSDB.EnrollProgram instance);
    partial void UpdateEnrollProgram(AlumniSNSDB.EnrollProgram instance);
    partial void DeleteEnrollProgram(AlumniSNSDB.EnrollProgram instance);
    partial void InsertWorkplaceNature(AlumniSNSDB.WorkplaceNature instance);
    partial void UpdateWorkplaceNature(AlumniSNSDB.WorkplaceNature instance);
    partial void DeleteWorkplaceNature(AlumniSNSDB.WorkplaceNature instance);
    partial void InsertEnrollSchool(AlumniSNSDB.EnrollSchool instance);
    partial void UpdateEnrollSchool(AlumniSNSDB.EnrollSchool instance);
    partial void DeleteEnrollSchool(AlumniSNSDB.EnrollSchool instance);
    partial void InsertUser(AlumniSNSDB.User instance);
    partial void UpdateUser(AlumniSNSDB.User instance);
    partial void DeleteUser(AlumniSNSDB.User instance);
    #endregion
		
		public AlumniSNSDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AlumniSNSConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AlumniSNSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumniSNSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumniSNSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlumniSNSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AlumniSNSDB.EnrollProgram> EnrollProgram
		{
			get
			{
				return this.GetTable<AlumniSNSDB.EnrollProgram>();
			}
		}
		
		public System.Data.Linq.Table<AlumniSNSDB.WorkplaceNature> WorkplaceNature
		{
			get
			{
				return this.GetTable<AlumniSNSDB.WorkplaceNature>();
			}
		}
		
		public System.Data.Linq.Table<AlumniSNSDB.EnrollSchool> EnrollSchool
		{
			get
			{
				return this.GetTable<AlumniSNSDB.EnrollSchool>();
			}
		}
		
		public System.Data.Linq.Table<AlumniSNSDB.User> User
		{
			get
			{
				return this.GetTable<AlumniSNSDB.User>();
			}
		}
	}
}
namespace AlumniSNSDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[Table(Name="dbo.EnrollProgram")]
	public partial class EnrollProgram : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProgramID;
		
		private int _SchoolID;
		
		private string _ProgramName;
		
		private EntityRef<EnrollSchool> _EnrollSchool;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProgramIDChanging(int value);
    partial void OnProgramIDChanged();
    partial void OnSchoolIDChanging(int value);
    partial void OnSchoolIDChanged();
    partial void OnProgramNameChanging(string value);
    partial void OnProgramNameChanged();
    #endregion
		
		public EnrollProgram()
		{
			this._EnrollSchool = default(EntityRef<EnrollSchool>);
			OnCreated();
		}
		
		[Column(Storage="_ProgramID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ProgramID
		{
			get
			{
				return this._ProgramID;
			}
			set
			{
				if ((this._ProgramID != value))
				{
					this.OnProgramIDChanging(value);
					this.SendPropertyChanging();
					this._ProgramID = value;
					this.SendPropertyChanged("ProgramID");
					this.OnProgramIDChanged();
				}
			}
		}
		
		[Column(Storage="_SchoolID", DbType="Int NOT NULL")]
		public int SchoolID
		{
			get
			{
				return this._SchoolID;
			}
			set
			{
				if ((this._SchoolID != value))
				{
					if (this._EnrollSchool.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSchoolIDChanging(value);
					this.SendPropertyChanging();
					this._SchoolID = value;
					this.SendPropertyChanged("SchoolID");
					this.OnSchoolIDChanged();
				}
			}
		}
		
		[Column(Storage="_ProgramName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ProgramName
		{
			get
			{
				return this._ProgramName;
			}
			set
			{
				if ((this._ProgramName != value))
				{
					this.OnProgramNameChanging(value);
					this.SendPropertyChanging();
					this._ProgramName = value;
					this.SendPropertyChanged("ProgramName");
					this.OnProgramNameChanged();
				}
			}
		}
		
		[Association(Name="EnrollSchool_EnrollProgram", Storage="_EnrollSchool", ThisKey="SchoolID", OtherKey="SchoolID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public EnrollSchool EnrollSchool
		{
			get
			{
				return this._EnrollSchool.Entity;
			}
			set
			{
				EnrollSchool previousValue = this._EnrollSchool.Entity;
				if (((previousValue != value) 
							|| (this._EnrollSchool.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._EnrollSchool.Entity = null;
						previousValue.EnrollProgram.Remove(this);
					}
					this._EnrollSchool.Entity = value;
					if ((value != null))
					{
						value.EnrollProgram.Add(this);
						this._SchoolID = value.SchoolID;
					}
					else
					{
						this._SchoolID = default(int);
					}
					this.SendPropertyChanged("EnrollSchool");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.WorkplaceNature")]
	public partial class WorkplaceNature : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NatureID;
		
		private int _NatureCode;
		
		private string _NatureName;
		
		private EntitySet<User> _User;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNatureIDChanging(int value);
    partial void OnNatureIDChanged();
    partial void OnNatureCodeChanging(int value);
    partial void OnNatureCodeChanged();
    partial void OnNatureNameChanging(string value);
    partial void OnNatureNameChanged();
    #endregion
		
		public WorkplaceNature()
		{
			this._User = new EntitySet<User>(new Action<User>(this.attach_User), new Action<User>(this.detach_User));
			OnCreated();
		}
		
		[Column(Storage="_NatureID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NatureID
		{
			get
			{
				return this._NatureID;
			}
			set
			{
				if ((this._NatureID != value))
				{
					this.OnNatureIDChanging(value);
					this.SendPropertyChanging();
					this._NatureID = value;
					this.SendPropertyChanged("NatureID");
					this.OnNatureIDChanged();
				}
			}
		}
		
		[Column(Storage="_NatureCode", DbType="Int NOT NULL")]
		public int NatureCode
		{
			get
			{
				return this._NatureCode;
			}
			set
			{
				if ((this._NatureCode != value))
				{
					this.OnNatureCodeChanging(value);
					this.SendPropertyChanging();
					this._NatureCode = value;
					this.SendPropertyChanged("NatureCode");
					this.OnNatureCodeChanged();
				}
			}
		}
		
		[Column(Storage="_NatureName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NatureName
		{
			get
			{
				return this._NatureName;
			}
			set
			{
				if ((this._NatureName != value))
				{
					this.OnNatureNameChanging(value);
					this.SendPropertyChanging();
					this._NatureName = value;
					this.SendPropertyChanged("NatureName");
					this.OnNatureNameChanged();
				}
			}
		}
		
		[Association(Name="WorkplaceNature_User", Storage="_User", ThisKey="NatureID", OtherKey="WorkplaceNatureID")]
		public EntitySet<User> User
		{
			get
			{
				return this._User;
			}
			set
			{
				this._User.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_User(User entity)
		{
			this.SendPropertyChanging();
			entity.WorkplaceNature = this;
		}
		
		private void detach_User(User entity)
		{
			this.SendPropertyChanging();
			entity.WorkplaceNature = null;
		}
	}
	
	[Table(Name="dbo.EnrollSchool")]
	public partial class EnrollSchool : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SchoolID;
		
		private string _SchoolName;
		
		private EntitySet<EnrollProgram> _EnrollProgram;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSchoolIDChanging(int value);
    partial void OnSchoolIDChanged();
    partial void OnSchoolNameChanging(string value);
    partial void OnSchoolNameChanged();
    #endregion
		
		public EnrollSchool()
		{
			this._EnrollProgram = new EntitySet<EnrollProgram>(new Action<EnrollProgram>(this.attach_EnrollProgram), new Action<EnrollProgram>(this.detach_EnrollProgram));
			OnCreated();
		}
		
		[Column(Storage="_SchoolID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SchoolID
		{
			get
			{
				return this._SchoolID;
			}
			set
			{
				if ((this._SchoolID != value))
				{
					this.OnSchoolIDChanging(value);
					this.SendPropertyChanging();
					this._SchoolID = value;
					this.SendPropertyChanged("SchoolID");
					this.OnSchoolIDChanged();
				}
			}
		}
		
		[Column(Storage="_SchoolName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string SchoolName
		{
			get
			{
				return this._SchoolName;
			}
			set
			{
				if ((this._SchoolName != value))
				{
					this.OnSchoolNameChanging(value);
					this.SendPropertyChanging();
					this._SchoolName = value;
					this.SendPropertyChanged("SchoolName");
					this.OnSchoolNameChanged();
				}
			}
		}
		
		[Association(Name="EnrollSchool_EnrollProgram", Storage="_EnrollProgram", ThisKey="SchoolID", OtherKey="SchoolID")]
		public EntitySet<EnrollProgram> EnrollProgram
		{
			get
			{
				return this._EnrollProgram;
			}
			set
			{
				this._EnrollProgram.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_EnrollProgram(EnrollProgram entity)
		{
			this.SendPropertyChanging();
			entity.EnrollSchool = this;
		}
		
		private void detach_EnrollProgram(EnrollProgram entity)
		{
			this.SendPropertyChanging();
			entity.EnrollSchool = null;
		}
	}
	
	[Table(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _UserName;
		
		private string _PassWord;
		
		private string _Name;
		
		private System.Nullable<int> _Sex;
		
		private System.Nullable<System.DateTime> _BirthDate;
		
		private string _LiveCountry;
		
		private string _LiveProvince;
		
		private string _LiveCity;
		
		private System.Nullable<int> _WorkplaceNatureID;
		
		private string _WorkplaceName;
		
		private string _WorkTitle;
		
		private string _MailingAddress;
		
		private string _FixedPhone;
		
		private string _MobilePhone;
		
		private string _EMail;
		
		private string _QQNo;
		
		private string _WeChatID;
		
		private string _ClassNo;
		
		private string _StudentNo;
		
		private System.DateTime _EnrollDate;
		
		private int _EnrollSchoolID;
		
		private int _EnrollProgramID;
		
		private System.Nullable<System.DateTime> _GraduateDate;
		
		private EntityRef<WorkplaceNature> _WorkplaceNature;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnSexChanging(System.Nullable<int> value);
    partial void OnSexChanged();
    partial void OnBirthDateChanging(System.Nullable<System.DateTime> value);
    partial void OnBirthDateChanged();
    partial void OnLiveCountryChanging(string value);
    partial void OnLiveCountryChanged();
    partial void OnLiveProvinceChanging(string value);
    partial void OnLiveProvinceChanged();
    partial void OnLiveCityChanging(string value);
    partial void OnLiveCityChanged();
    partial void OnWorkplaceNatureIDChanging(System.Nullable<int> value);
    partial void OnWorkplaceNatureIDChanged();
    partial void OnWorkplaceNameChanging(string value);
    partial void OnWorkplaceNameChanged();
    partial void OnWorkTitleChanging(string value);
    partial void OnWorkTitleChanged();
    partial void OnMailingAddressChanging(string value);
    partial void OnMailingAddressChanged();
    partial void OnFixedPhoneChanging(string value);
    partial void OnFixedPhoneChanged();
    partial void OnMobilePhoneChanging(string value);
    partial void OnMobilePhoneChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnQQNoChanging(string value);
    partial void OnQQNoChanged();
    partial void OnWeChatIDChanging(string value);
    partial void OnWeChatIDChanged();
    partial void OnClassNoChanging(string value);
    partial void OnClassNoChanged();
    partial void OnStudentNoChanging(string value);
    partial void OnStudentNoChanged();
    partial void OnEnrollDateChanging(System.DateTime value);
    partial void OnEnrollDateChanged();
    partial void OnEnrollSchoolIDChanging(int value);
    partial void OnEnrollSchoolIDChanged();
    partial void OnEnrollProgramIDChanging(int value);
    partial void OnEnrollProgramIDChanged();
    partial void OnGraduateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGraduateDateChanged();
    #endregion
		
		public User()
		{
			this._WorkplaceNature = default(EntityRef<WorkplaceNature>);
			OnCreated();
		}
		
		[Column(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[Column(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_Sex", DbType="Int")]
		public System.Nullable<int> Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[Column(Storage="_BirthDate", DbType="Date")]
		public System.Nullable<System.DateTime> BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this.OnBirthDateChanging(value);
					this.SendPropertyChanging();
					this._BirthDate = value;
					this.SendPropertyChanged("BirthDate");
					this.OnBirthDateChanged();
				}
			}
		}
		
		[Column(Storage="_LiveCountry", DbType="NVarChar(30)")]
		public string LiveCountry
		{
			get
			{
				return this._LiveCountry;
			}
			set
			{
				if ((this._LiveCountry != value))
				{
					this.OnLiveCountryChanging(value);
					this.SendPropertyChanging();
					this._LiveCountry = value;
					this.SendPropertyChanged("LiveCountry");
					this.OnLiveCountryChanged();
				}
			}
		}
		
		[Column(Storage="_LiveProvince", DbType="NVarChar(30)")]
		public string LiveProvince
		{
			get
			{
				return this._LiveProvince;
			}
			set
			{
				if ((this._LiveProvince != value))
				{
					this.OnLiveProvinceChanging(value);
					this.SendPropertyChanging();
					this._LiveProvince = value;
					this.SendPropertyChanged("LiveProvince");
					this.OnLiveProvinceChanged();
				}
			}
		}
		
		[Column(Storage="_LiveCity", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string LiveCity
		{
			get
			{
				return this._LiveCity;
			}
			set
			{
				if ((this._LiveCity != value))
				{
					this.OnLiveCityChanging(value);
					this.SendPropertyChanging();
					this._LiveCity = value;
					this.SendPropertyChanged("LiveCity");
					this.OnLiveCityChanged();
				}
			}
		}
		
		[Column(Storage="_WorkplaceNatureID", DbType="Int")]
		public System.Nullable<int> WorkplaceNatureID
		{
			get
			{
				return this._WorkplaceNatureID;
			}
			set
			{
				if ((this._WorkplaceNatureID != value))
				{
					if (this._WorkplaceNature.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWorkplaceNatureIDChanging(value);
					this.SendPropertyChanging();
					this._WorkplaceNatureID = value;
					this.SendPropertyChanged("WorkplaceNatureID");
					this.OnWorkplaceNatureIDChanged();
				}
			}
		}
		
		[Column(Storage="_WorkplaceName", DbType="NVarChar(100)")]
		public string WorkplaceName
		{
			get
			{
				return this._WorkplaceName;
			}
			set
			{
				if ((this._WorkplaceName != value))
				{
					this.OnWorkplaceNameChanging(value);
					this.SendPropertyChanging();
					this._WorkplaceName = value;
					this.SendPropertyChanged("WorkplaceName");
					this.OnWorkplaceNameChanged();
				}
			}
		}
		
		[Column(Storage="_WorkTitle", DbType="NVarChar(50)")]
		public string WorkTitle
		{
			get
			{
				return this._WorkTitle;
			}
			set
			{
				if ((this._WorkTitle != value))
				{
					this.OnWorkTitleChanging(value);
					this.SendPropertyChanging();
					this._WorkTitle = value;
					this.SendPropertyChanged("WorkTitle");
					this.OnWorkTitleChanged();
				}
			}
		}
		
		[Column(Storage="_MailingAddress", DbType="NVarChar(MAX)")]
		public string MailingAddress
		{
			get
			{
				return this._MailingAddress;
			}
			set
			{
				if ((this._MailingAddress != value))
				{
					this.OnMailingAddressChanging(value);
					this.SendPropertyChanging();
					this._MailingAddress = value;
					this.SendPropertyChanged("MailingAddress");
					this.OnMailingAddressChanged();
				}
			}
		}
		
		[Column(Storage="_FixedPhone", DbType="NVarChar(20)")]
		public string FixedPhone
		{
			get
			{
				return this._FixedPhone;
			}
			set
			{
				if ((this._FixedPhone != value))
				{
					this.OnFixedPhoneChanging(value);
					this.SendPropertyChanging();
					this._FixedPhone = value;
					this.SendPropertyChanged("FixedPhone");
					this.OnFixedPhoneChanged();
				}
			}
		}
		
		[Column(Storage="_MobilePhone", DbType="NVarChar(20)")]
		public string MobilePhone
		{
			get
			{
				return this._MobilePhone;
			}
			set
			{
				if ((this._MobilePhone != value))
				{
					this.OnMobilePhoneChanging(value);
					this.SendPropertyChanging();
					this._MobilePhone = value;
					this.SendPropertyChanged("MobilePhone");
					this.OnMobilePhoneChanged();
				}
			}
		}
		
		[Column(Storage="_EMail", DbType="NVarChar(100)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[Column(Storage="_QQNo", DbType="NVarChar(20)")]
		public string QQNo
		{
			get
			{
				return this._QQNo;
			}
			set
			{
				if ((this._QQNo != value))
				{
					this.OnQQNoChanging(value);
					this.SendPropertyChanging();
					this._QQNo = value;
					this.SendPropertyChanged("QQNo");
					this.OnQQNoChanged();
				}
			}
		}
		
		[Column(Storage="_WeChatID", DbType="NVarChar(50)")]
		public string WeChatID
		{
			get
			{
				return this._WeChatID;
			}
			set
			{
				if ((this._WeChatID != value))
				{
					this.OnWeChatIDChanging(value);
					this.SendPropertyChanging();
					this._WeChatID = value;
					this.SendPropertyChanged("WeChatID");
					this.OnWeChatIDChanged();
				}
			}
		}
		
		[Column(Storage="_ClassNo", DbType="NVarChar(20)")]
		public string ClassNo
		{
			get
			{
				return this._ClassNo;
			}
			set
			{
				if ((this._ClassNo != value))
				{
					this.OnClassNoChanging(value);
					this.SendPropertyChanging();
					this._ClassNo = value;
					this.SendPropertyChanged("ClassNo");
					this.OnClassNoChanged();
				}
			}
		}
		
		[Column(Storage="_StudentNo", DbType="NVarChar(30)")]
		public string StudentNo
		{
			get
			{
				return this._StudentNo;
			}
			set
			{
				if ((this._StudentNo != value))
				{
					this.OnStudentNoChanging(value);
					this.SendPropertyChanging();
					this._StudentNo = value;
					this.SendPropertyChanged("StudentNo");
					this.OnStudentNoChanged();
				}
			}
		}
		
		[Column(Storage="_EnrollDate", DbType="Date NOT NULL")]
		public System.DateTime EnrollDate
		{
			get
			{
				return this._EnrollDate;
			}
			set
			{
				if ((this._EnrollDate != value))
				{
					this.OnEnrollDateChanging(value);
					this.SendPropertyChanging();
					this._EnrollDate = value;
					this.SendPropertyChanged("EnrollDate");
					this.OnEnrollDateChanged();
				}
			}
		}
		
		[Column(Storage="_EnrollSchoolID", DbType="Int NOT NULL")]
		public int EnrollSchoolID
		{
			get
			{
				return this._EnrollSchoolID;
			}
			set
			{
				if ((this._EnrollSchoolID != value))
				{
					this.OnEnrollSchoolIDChanging(value);
					this.SendPropertyChanging();
					this._EnrollSchoolID = value;
					this.SendPropertyChanged("EnrollSchoolID");
					this.OnEnrollSchoolIDChanged();
				}
			}
		}
		
		[Column(Storage="_EnrollProgramID", DbType="Int NOT NULL")]
		public int EnrollProgramID
		{
			get
			{
				return this._EnrollProgramID;
			}
			set
			{
				if ((this._EnrollProgramID != value))
				{
					this.OnEnrollProgramIDChanging(value);
					this.SendPropertyChanging();
					this._EnrollProgramID = value;
					this.SendPropertyChanged("EnrollProgramID");
					this.OnEnrollProgramIDChanged();
				}
			}
		}
		
		[Column(Storage="_GraduateDate", DbType="Date")]
		public System.Nullable<System.DateTime> GraduateDate
		{
			get
			{
				return this._GraduateDate;
			}
			set
			{
				if ((this._GraduateDate != value))
				{
					this.OnGraduateDateChanging(value);
					this.SendPropertyChanging();
					this._GraduateDate = value;
					this.SendPropertyChanged("GraduateDate");
					this.OnGraduateDateChanged();
				}
			}
		}
		
		[Association(Name="WorkplaceNature_User", Storage="_WorkplaceNature", ThisKey="WorkplaceNatureID", OtherKey="NatureID", IsForeignKey=true)]
		public WorkplaceNature WorkplaceNature
		{
			get
			{
				return this._WorkplaceNature.Entity;
			}
			set
			{
				WorkplaceNature previousValue = this._WorkplaceNature.Entity;
				if (((previousValue != value) 
							|| (this._WorkplaceNature.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._WorkplaceNature.Entity = null;
						previousValue.User.Remove(this);
					}
					this._WorkplaceNature.Entity = value;
					if ((value != null))
					{
						value.User.Add(this);
						this._WorkplaceNatureID = value.NatureID;
					}
					else
					{
						this._WorkplaceNatureID = default(Nullable<int>);
					}
					this.SendPropertyChanged("WorkplaceNature");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
