<?xml version="1.0" encoding="utf-8"?><Database Name="AlumniSNS" EntityNamespace="SNSDatabase" Class="SNSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\AlumniSNS.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AlumniSNSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.EmployCategory" Member="EmployCategory">
    <Type Name="EmployCategory">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EmployCategory_User" Member="User" ThisKey="CategoryID" OtherKey="EmployCategoryID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.WorkplaceNature" Member="WorkplaceNature">
    <Type Name="WorkplaceNature">
      <Column Name="NatureID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NatureCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NatureName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="WorkplaceNature_User" Member="User" ThisKey="NatureID" OtherKey="WorkplaceNatureID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.EnrollProgram" Member="EnrollProgram">
    <Type Name="EnrollProgram">
      <Column Name="ProgramID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProgramName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="EnrollProgram_User" Member="User" ThisKey="ProgramID" OtherKey="EnrollProgramID" Type="User" />
      <Association Name="EnrollSchool_EnrollProgram" Member="EnrollSchool" ThisKey="SchoolID" OtherKey="SchoolID" Type="EnrollSchool" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.EnrollSchool" Member="EnrollSchool">
    <Type Name="EnrollSchool">
      <Column Name="SchoolID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SchoolName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="EnrollSchool_EnrollProgram" Member="EnrollProgram" ThisKey="SchoolID" OtherKey="SchoolID" Type="EnrollProgram" />
      <Association Name="EnrollSchool_User" Member="User" ThisKey="SchoolID" OtherKey="EnrollSchoolID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.LiveCity" Member="LiveCity">
    <Type Name="LiveCity">
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProvinceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LiveProvince_LiveCity" Member="LiveProvince" ThisKey="ProvinceID" OtherKey="ProvinceID" Type="LiveProvince" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LiveProvince" Member="LiveProvince">
    <Type Name="LiveProvince">
      <Column Name="ProvinceID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProvinceName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LiveProvince_LiveCity" Member="LiveCity" ThisKey="ProvinceID" OtherKey="ProvinceID" Type="LiveCity" />
      <Association Name="LiveProvince_User" Member="User" ThisKey="ProvinceID" OtherKey="LiveProvinceID" Type="User" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="User">
    <Type Name="User">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sex" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="LiveProvinceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LiveCityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkplaceNatureID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WorkplaceName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WorkTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MailingAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FixedPhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="QQNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="WeChatID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ClassNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StudentNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="EnrollDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="EnrollSchoolID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EnrollProgramID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GraduateDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="EmployCategory_User" Member="EmployCategory" ThisKey="EmployCategoryID" OtherKey="CategoryID" Type="EmployCategory" IsForeignKey="true" />
      <Association Name="EnrollProgram_User" Member="EnrollProgram" ThisKey="EnrollProgramID" OtherKey="ProgramID" Type="EnrollProgram" IsForeignKey="true" />
      <Association Name="EnrollSchool_User" Member="EnrollSchool" ThisKey="EnrollSchoolID" OtherKey="SchoolID" Type="EnrollSchool" IsForeignKey="true" />
      <Association Name="LiveProvince_User" Member="LiveProvince" ThisKey="LiveProvinceID" OtherKey="ProvinceID" Type="LiveProvince" IsForeignKey="true" />
      <Association Name="WorkplaceNature_User" Member="WorkplaceNature" ThisKey="WorkplaceNatureID" OtherKey="NatureID" Type="WorkplaceNature" IsForeignKey="true" />
    </Type>
  </Table>
</Database>