<?xml version="1.0" encoding="utf-8"?><Database Name="Alumni" EntityNamespace="AlumniDB" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Alumni.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Users_Articles" Member="Articles" ThisKey="UserID" OtherKey="PublishUserID" Type="Articles" />
    </Type>
  </Table>
  <Table Name="dbo.Configs" Member="Configs">
    <Type Name="Configs">
      <Column Name="GlobalTemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ArticlesPerPage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Templates_Configs" Member="Templates" ThisKey="GlobalTemplateID" OtherKey="TemplateID" Type="Templates" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Donations" Member="Donations">
    <Type Name="Donations">
      <Column Name="DonationId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Links" Member="Links">
    <Type Name="Links">
      <Column Name="LinkID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LinkName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LinkURL" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Templates" Member="Templates">
    <Type Name="Templates">
      <Column Name="TemplateID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentTemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubTemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TemplatePath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Templates_Configs" Member="Configs" ThisKey="TemplateID" OtherKey="GlobalTemplateID" Type="Configs" />
    </Type>
  </Table>
  <Table Name="dbo.Articles" Member="Articles">
    <Type Name="Articles">
      <Column Name="ArticleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ColumnID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubTemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublishUserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="VisitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsStickTop" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PictureURL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Source" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Users_Articles" Member="Users" ThisKey="PublishUserID" OtherKey="UserID" Type="Users" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Columns_Articles" Member="Columns" ThisKey="ColumnID" OtherKey="ColumnID" Type="Columns" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Columns" Member="Columns">
    <Type Name="Columns">
      <Column Name="ColumnID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParentColumnID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubTemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ColumnName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsExternalLink" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExternalLinkURL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Columns_Articles" Member="Articles" ThisKey="ColumnID" OtherKey="ColumnID" Type="Articles" />
    </Type>
  </Table>
</Database>