<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="deleteTitle.aspx.cs" Inherits="Alumni.Manage.tab.deleteTitle" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:Label ID="Label1" runat="server" Text="当前位置：删除栏目"></asp:Label>
    
        <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" 
            AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" 
            DataKeyNames="ColumnID" EnableModelValidation="True" CellPadding="4" 
            ForeColor="#333333" GridLines="None" Width="100%">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="ColumnName" HeaderText="栏目名" 
                    SortExpression="ColumnName" />
                <asp:CheckBoxField DataField="Visible" HeaderText="可见性" 
                    SortExpression="Visible" />
                <asp:CheckBoxField DataField="Deletable" HeaderText="可删除性" 
                    SortExpression="Deletable" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        </asp:GridView>
    
    </div>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:AlumniConnectionString %>" 
        SelectCommand="SELECT * FROM [Columns]" 
        DeleteCommand="DELETE FROM [Columns] WHERE [ColumnID] = @ColumnID" 
        InsertCommand="INSERT INTO [Columns] ([ParentColumnID], [SubTemplateID], [ColumnName], [Visible], [Deletable], [IsSpecialCommand], [SpecialCommandName], [SpecialCommandArgument]) VALUES (@ParentColumnID, @SubTemplateID, @ColumnName, @Visible, @Deletable, @IsSpecialCommand, @SpecialCommandName, @SpecialCommandArgument)" 
        UpdateCommand="UPDATE [Columns] SET [ParentColumnID] = @ParentColumnID, [SubTemplateID] = @SubTemplateID, [ColumnName] = @ColumnName, [Visible] = @Visible, [Deletable] = @Deletable, [IsSpecialCommand] = @IsSpecialCommand, [SpecialCommandName] = @SpecialCommandName, [SpecialCommandArgument] = @SpecialCommandArgument WHERE [ColumnID] = @ColumnID">
        <DeleteParameters>
            <asp:Parameter Name="ColumnID" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="ParentColumnID" Type="Int32" />
            <asp:Parameter Name="SubTemplateID" Type="Int32" />
            <asp:Parameter Name="ColumnName" Type="String" />
            <asp:Parameter Name="Visible" Type="Boolean" />
            <asp:Parameter Name="Deletable" Type="Boolean" />
            <asp:Parameter Name="IsSpecialCommand" Type="Boolean" />
            <asp:Parameter Name="SpecialCommandName" Type="String" />
            <asp:Parameter Name="SpecialCommandArgument" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="ParentColumnID" Type="Int32" />
            <asp:Parameter Name="SubTemplateID" Type="Int32" />
            <asp:Parameter Name="ColumnName" Type="String" />
            <asp:Parameter Name="Visible" Type="Boolean" />
            <asp:Parameter Name="Deletable" Type="Boolean" />
            <asp:Parameter Name="IsSpecialCommand" Type="Boolean" />
            <asp:Parameter Name="SpecialCommandName" Type="String" />
            <asp:Parameter Name="SpecialCommandArgument" Type="String" />
            <asp:Parameter Name="ColumnID" Type="Int32" />
        </UpdateParameters>
    </asp:SqlDataSource>
    </form>
</body>
</html>
